{% set name = "atomate" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6557b8bc9963dd2f3001f9c0dc79468004fdff3a008823bb349a3ad526ea59b0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pip
    - custodian >=2018.6.11
    - fireworks >=1.4.0
    - maggma >=0.39.0
    - monty >=1.0.2
    - numpy <1.22.0,>=1.20.3
    - tqdm >=4.7.4
    - six
    - pymatgen >=2023.7.20
    - pymatgen-analysis-diffusion
    - pymatgen-analysis-defects
    - pydash >=4.1.0
    - paramiko >=2.4.2
    - pathlib2
    - matplotlib-base >=1.5.2
    - phonopy >=1.10.8
    - pymongo >=4.0

test:
  imports:
    - atomate
  commands:
    - pip check

about:
  home: https://hackingmaterials.github.io/atomate
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE
  summary: atomate is a powerful software for computational materials science and contains pre-built workflows.

  description: |
    atomate is a software for computational materials science that 
    contains pre-built workflows to compute and analyze the properties 
    of materials.
  doc_url: https://hackingmaterials.github.io/atomate
  dev_url: https://github.com/hackingmaterials/atomate

extra:
  recipe-maintainers:
    - jan-janssen
