schema_version: 1

context:
  name: atomate
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/atomate-${{ version }}.tar.gz
  sha256: 6557b8bc9963dd2f3001f9c0dc79468004fdff3a008823bb349a3ad526ea59b0

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - custodian >=2023.7.22
    - fireworks >=2.0.3
    - maggma >=0.51.25
    - monty >=2023.5.8
    - networkx
    - numpy
    - pandas
    - paramiko
    - pydash >=7.0.6
    - pymatgen-analysis-diffusion >=2023.8.15
    - pymatgen-analysis-defects >=2023.7.24
    - pymatgen >=2023.7.20
    - pymongo
    - pyyaml >=5.1.2
    - ruamel.yaml
    - scipy
    - tqdm >=4.65.0

tests:
  - python:
      imports:
        - atomate
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: atomate has implementations of FireWorks workflows for Materials Science
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/hackingmaterials/atomate

extra:
  recipe-maintainers:
    - jan-janssen
