travis:
  secure:
    BINSTAR_TOKEN: afKKeRRgXsDJuamthyJlxhNK1cJB42v1ahh4OkyMuUE3G7/66e936/t43kkbhH56pLvNX3p5/Y6Ng51eFhO+e7B8wOJvYNo4I+N19KX6FumkD2kTF/NEK1TjUipiAO57mtv9Ls2/De+B7s04/iuceG7GLqiaUUuUjLVuYts0KdWqWRyH1LFSfdiFVnH4E4SQRIB11lneSla3F6hk2CEKnLn4ewNFvq58Mlw8sFuhYKhD5I8AeDT58HHS6aChOS5tES3BPvEOx6etfAIS078neQWizl0em5SGcwuiJOyZCG1zOA7evKa6eR1ufNTOb6FOfxMC51FDRD+4aTNgLT//PNvslZb67E7LBMj8SDPgym5ui1WYT4znYZIEUeQOA3jKVKdFV5FenB8uobppwnIsWM0AJ69HOlNN6wWZYI+RUa2ODh/R32DlIc60YVfyq3ld5Wo0btoOemS5v1NMxyZbwjnhJK3fY3tVXAtcfiAoOev7JY0OK/vAPx+i/n05EycYsksRm/QfbF4+dAAaUuJzQu0ZZSv8l22t7eZkJFdVjRo3dvAQlcuKmKyzGZMwTuI8lSSPoTb6PvNSQnFPGDwp8ouIC9zG1tZi0B9lsuheoNu+7LKmAzTQO6BrqMwms8a37MpkwKDHq+qQcdooUgq6YTW0dXAXoTpmOKMJ4rjM778=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
